parameters:
- name: 'containerRegistry'
  default: ''
  type: string
- name: 'repository'
  default: ''
  type: string
variables:
  tag: '$(Build.BuildId)'
jobs:
- job: buildAndPush
  steps:
    - task: Docker@2      
      inputs:
        containerRegistry: ${{ parameters.containerRegistry }}
        repository: ${{ parameters.repository }}
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags:
          $(tag)
    - publish: '$(Build.SourcesDirectory)/k8s' # directory where my kubernetes files are stored
      artifact: manifests
