stages:
- stage: Build_and_Push
  displayName: Build and Push Image to Docker Registry
  jobs:
    - job: Push
      steps:
      - task: Docker@2      
        inputs:
          containerRegistry: $(containerRegistry)
          repository: $(repository)
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags:
            $(tag)
      - publish: '$(Build.SourcesDirectory)/k8s' # directory where my kubernetes files are stored
        artifact: manifests