parameters:
- name: 'containerRegistry'
  default: ''
  type: string
- name: 'kubeConnection'
  default: 'Kubernetes Connection'
  type: string
- name: 'repository'
  default: ''
  type: string
- name: 'tag'
  default: ''
  type: string
jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      environment:
        name: 'homologacao'
        resourceName: 'rails-project'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: manifests
            - task: KubernetesManifest@0
              displayName: Create imagePullSecret
              inputs:
                  action: createSecret
                  secretName: 'creator-secret-rails'
                  dockerRegistryEndpoint: 'Docker Registry'
                  namespace: 'rails-project'
                  kubernetesServiceConnection: ${{ parameters.kubeConnection }}
            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes cluster
              inputs:
                action: deploy
                namespace: 'rails-project'
                kubernetesServiceConnection: ${{ parameters.kubeConnection }}
                manifests: |
                    $(Pipeline.Workspace)/manifests/*.yaml
                imagePullSecrets: |
                    $(imagePullSecret)
                containers: |
                    ${{ parameters.containerRegistry }}/${{ parameters.repository }}:lts
